# trapeze config file
# update by running `npx trapeze run config.yaml`

vars:
  BUNDLE_ID:
    default: ch.lucabruegger.frienradar
  PACKAGE_NAME:
    default: ch.lucabruegger.frienradar
  VERSION:
    default: 1.02

platforms:
  ios:
    targets:
      Frienradar:
        bundleId: $BUNDLE_ID
        incrementBuild: true
        productName: Frienradar
        displayName: Frienradar
        version: $VERSION

        entitlements:
          - com.apple.developer.associated-domains: [
              "applinks:frienradar.com",
              "webcredentials:frienradar.com"
            ]
  android:
    appName: Frienradar
    incrementVersionCode: true
    versionName: $VERSION
    packageName: $PACKAGE_NAME
