vars:
  BUNDLE_ID:
    default: ch.lucabruegger.frienradar
  PACKAGE_NAME:
    default: ch.lucabruegger.frienradar

platforms:
  ios:
    targets:
      Frienradar:
        bundleId: $BUNDLE_ID
        incrementBuild: true
        productName: Frienradar
        displayName: Frienradar
        version: 1

        entitlements:
          - com.apple.developer.associated-domains: [
              "applinks:frienradar.com",
              "webcredentials:frienradar.com"
            ]
  android:
    packageName: $PACKAGE_NAME
